In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('stage3.csv')

In [3]:
df.describe()

,incident_id,n_killed,n_injured,congressional_district,latitude,longitude,n_guns_involved,state_house_district,state_senate_district
count,2.396770e+05,239677.000000,239677.000000,227733.000000,231754.000000,231754.000000,140226.000000,200905.000000,207342.00000
mean,5.593343e+05,0.252290,0.494007,8.001265,37.546598,-89.338348,1.372442,55.447132,20.47711
std,2.931287e+05,0.521779,0.729952,8.480835,5.130763,14.359546,4.678202,42.048117,14.20456
min,9.211400e+04,0.000000,0.000000,0.000000,19.111400,-171.429000,1.000000,1.000000,1.00000
25%,3.085450e+05,0.000000,0.000000,2.000000,33.903400,-94.158725,1.000000,21.000000,9.00000
50%,5.435870e+05,0.000000,0.000000,5.000000,38.570600,-86.249600,1.000000,47.000000,19.00000
75%,8.172280e+05,0.000000,1.000000,10.000000,41.437375,-80.048625,1.000000,84.000000,30.00000
max,1.083472e+06,50.000000,53.000000,53.000000,71.336800,97.433100,400.000000,901.000000,94.00000

In [4]:
df.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'address', 'n_killed',
       'n_injured', 'incident_url', 'source_url',
       'incident_url_fields_missing', 'congressional_district', 'gun_stolen',
       'gun_type', 'incident_characteristics', 'latitude',
       'location_description', 'longitude', 'n_guns_involved', 'notes',
       'participant_age', 'participant_age_group', 'participant_gender',
       'participant_name', 'participant_relationship', 'participant_status',
       'participant_type', 'sources', 'state_house_district',
       'state_senate_district'],
      dtype='object')

In [5]:
df = df.drop(['incident_url', 'source_url', 'incident_url_fields_missing', 'sources', 'notes', 'address', 'participant_name', 'congressional_district','state_house_district', 'state_senate_district', 'latitude','longitude'], axis=1)

In [6]:
df.head()

,incident_id,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,location_description,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
0,461105,1/1/2013,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
1,460726,1/1/2013,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...
2,478855,1/1/2013,Ohio,Lorain,1,3,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",Cotton Club,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...
3,478925,1/5/2013,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...
4,478959,1/7/2013,North Carolina,Greensboro,2,2,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...

In [7]:
df['participant_gender'] =  df['participant_gender'].str.replace('[^A-Za-z\\|]+', '')
df['participant_status'] =  df['participant_status'].str.replace('[^A-Za-z\\|]+', '')
df['participant_age_group'] =  df['participant_age_group'].str.replace('[^A-Za-z\\|]+', '')
df['participant_type'] =  df['participant_type'].str.replace('[^A-Za-z\\|]+', '')

<ipython-input-7-82aeda6b7c6b>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['participant_gender'] =  df['participant_gender'].str.replace('[^A-Za-z\\|]+', '')
<ipython-input-7-82aeda6b7c6b>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['participant_status'] =  df['participant_status'].str.replace('[^A-Za-z\\|]+', '')
<ipython-input-7-82aeda6b7c6b>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['participant_age_group'] =  df['participant_age_group'].str.replace('[^A-Za-z\\|]+', '')
<ipython-input-7-82aeda6b7c6b>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['participant_type'] =  df['participant_type'].str.replace('[^A-Za-z\\|]+', '')

In [8]:
df['gender_list'] = df.participant_gender.str.split('\\|\\|')
df['status_list'] = df.participant_status.str.split('\\|\\|')
df['age_list'] = df.participant_age_group.str.split('\\|\\|')
df['type_list'] = df.participant_type.str.split('\\|\\|')

In [9]:
df

,incident_id,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,location_description,...,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,gender_list,status_list,age_list,type_list
0,461105,1/1/2013,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,...,0::20,Adult||Adult||Adult||Adult||Adult,Male||Male||Male||Female,NaN,Arrested||Injured||Injured||Injured||Injured,Victim||Victim||Victim||Victim||SubjectSuspect,"[Male, Male, Male, Female]","[Arrested, Injured, Injured, Injured, Injured]","[Adult, Adult, Adult, Adult, Adult]","[Victim, Victim, Victim, Victim, SubjectSuspect]"
1,460726,1/1/2013,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,0::20,Adult||Adult||Adult||Adult,Male,NaN,Killed||Injured||Injured||Injured,Victim||Victim||Victim||Victim||SubjectSuspect,[Male],"[Killed, Injured, Injured, Injured]","[Adult, Adult, Adult, Adult]","[Victim, Victim, Victim, Victim, SubjectSuspect]"
2,478855,1/1/2013,Ohio,Lorain,1,3,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",Cotton Club,...,0::25||1::31||2::33||3::34||4::33,Adult||Adult||Adult||Adult||Adult,Male||Male||Male||Male||Male,NaN,InjuredUnharmedArrested||UnharmedArrested||Kil...,SubjectSuspect||SubjectSuspect||Victim||Victim...,"[Male, Male, Male, Male, Male]","[InjuredUnharmedArrested, UnharmedArrested, Ki...","[Adult, Adult, Adult, Adult, Adult]","[SubjectSuspect, SubjectSuspect, Victim, Victi..."
3,478925,1/5/2013,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,...,0::29||1::33||2::56||3::33,Adult||Adult||Adult||Adult,Female||Male||Male||Male,NaN,Killed||Killed||Killed||Killed,Victim||Victim||Victim||SubjectSuspect,"[Female, Male, Male, Male]","[Killed, Killed, Killed, Killed]","[Adult, Adult, Adult, Adult]","[Victim, Victim, Victim, SubjectSuspect]"
4,478959,1/7/2013,North Carolina,Greensboro,2,2,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,0::18||1::46||2::14||3::47,Adult||Adult||Teen||Adult,Female||Male||Male||Female,3::Family,Injured||Injured||Killed||Killed,Victim||Victim||Victim||SubjectSuspect,"[Female, Male, Male, Female]","[Injured, Injured, Killed, Killed]","[Adult, Adult, Teen, Adult]","[Victim, Victim, Victim, SubjectSuspect]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,3/31/2018,Louisiana,Rayne,0,0,0::Unknown,0::Unknown,Shots Fired - No Injuries,NaN,...,0::25,Adult,Female,NaN,UnharmedArrested,SubjectSuspect,[Female],[UnharmedArrested],[Adult],[SubjectSuspect]
239673,1083139,3/31/2018,Louisiana,Natchitoches,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",Shop Rite,...,1::21,Adult||Adult,Male||Male,NaN,Killed||UnharmedArrested,Victim||SubjectSuspect,"[Male, Male]","[Killed, UnharmedArrested]","[Adult, Adult]","[Victim, SubjectSuspect]"
239674,1083151,3/31/2018,Louisiana,Gretna,0,1,0::Unknown,0::Unknown,Shot - Wounded/Injured,NaN,...,0::21,Adult,Male,NaN,Injured,Victim,[Male],[Injured],[Adult],[Victim]
239675,1082514,3/31/2018,Texas,Houston,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)",Vanderbilt Court apartments,...,0::42,Adult,Male,NaN,Killed,Victim,[Male],[Killed],[Adult],[Victim]
239676,1081940,3/31/2018,Maine,Norridgewock,2,0,0::Unknown||1::Unknown,0::Handgun||1::Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",NaN,...,0::58||1::62,Adult||Adult,Female||Male,1::Significant others - current or former,Killed||Killed,Victim||SubjectSuspect,"[Female, Male]","[Killed, Killed]","[Adult, Adult]","[Victim, SubjectSuspect]"

In [10]:
df = df[df['gender_list'].notna()]
df = df[df['status_list'].notna()]
df = df[df['age_list'].notna()]
df = df[df['type_list'].notna()]

In [11]:
df = df.drop(['participant_gender','participant_status','participant_age_group','participant_type'], axis=1)

In [12]:
df.isna().sum()

incident_id                      0
date                             0
state                            0
city_or_county                   0
n_killed                         0
n_injured                        0
gun_stolen                   79637
gun_type                     79612
incident_characteristics       232
location_description        158744
n_guns_involved              79612
participant_age              46431
participant_relationship    176944
gender_list                      0
status_list                      0
age_list                         0
type_list                        0
dtype: int64

In [13]:
df['male'] = df['gender_list'].apply(lambda x: x.count('Male'))
df['female'] = df['gender_list'].apply(lambda x: x.count('Female'))

In [14]:
df['Adult'] = df['age_list'].apply(lambda x: x.count('Adult'))
df['Teen'] = df['age_list'].apply(lambda x: x.count('Teen'))
df['Child'] = df['age_list'].apply(lambda x: x.count('Child'))

In [15]:
df['Victim'] = df['type_list'].apply(lambda x: x.count('Victim'))
df['Suspect'] = df['type_list'].apply(lambda x: sum('Suspect' in s in s for s in x))

In [16]:
df['Arrested'] = df['status_list'].apply(lambda x: sum('Arrested' in s in s for s in x))
df['Killed'] = df['status_list'].apply(lambda x:sum('Killed' in s in s for s in x))
df['Injured'] = df['status_list'].apply(lambda x: sum('Injured' in s in s for s in x))

In [17]:
df.incident_characteristics.values

array(['Shot - Wounded/Injured||Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)||Possession (gun(s) found during commission of other crimes)||Possession of gun by felon or prohibited person',
       'Shot - Wounded/Injured||Shot - Dead (murder, accidental, suicide)||Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)||Gang involvement',
       'Shot - Wounded/Injured||Shot - Dead (murder, accidental, suicide)||Shots Fired - No Injuries||Bar/club incident - in or around establishment',
       ..., 'Shot - Wounded/Injured',
       'Shot - Dead (murder, accidental, suicide)',
       'Shot - Dead (murder, accidental, suicide)||Suicide^||Murder/Suicide||Domestic Violence'],
      dtype=object)

In [18]:
df['date'] = pd.to_datetime(df['date'])
df

,incident_id,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,location_description,...,male,female,Adult,Teen,Child,Victim,Suspect,Arrested,Killed,Injured
0,461105,2013-01-01,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,...,3,1,5,0,0,4,1,1,0,4
1,460726,2013-01-01,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,1,0,4,0,0,4,1,0,1,3
2,478855,2013-01-01,Ohio,Lorain,1,3,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",Cotton Club,...,5,0,5,0,0,3,2,2,1,3
3,478925,2013-01-05,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,...,3,1,4,0,0,3,1,0,4,0
4,478959,2013-01-07,North Carolina,Greensboro,2,2,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,2,2,3,1,0,3,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,2018-03-31,Louisiana,Rayne,0,0,0::Unknown,0::Unknown,Shots Fired - No Injuries,NaN,...,0,1,1,0,0,0,1,1,0,0
239673,1083139,2018-03-31,Louisiana,Natchitoches,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",Shop Rite,...,2,0,2,0,0,1,1,1,1,0
239674,1083151,2018-03-31,Louisiana,Gretna,0,1,0::Unknown,0::Unknown,Shot - Wounded/Injured,NaN,...,1,0,1,0,0,1,0,0,0,1
239675,1082514,2018-03-31,Texas,Houston,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)",Vanderbilt Court apartments,...,1,0,1,0,0,1,0,0,1,0
239676,1081940,2018-03-31,Maine,Norridgewock,2,0,0::Unknown||1::Unknown,0::Handgun||1::Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",NaN,...,1,1,2,0,0,1,1,0,2,0

In [19]:
df['gun_stolen'] = df['gun_stolen'].str.replace('[^A-Za-z\\|]+', '')
df['gun_type'] = df['gun_type'].str.replace('[^A-Za-z\\|]+', '')

<ipython-input-19-dc66ac357375>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['gun_stolen'] = df['gun_stolen'].str.replace('[^A-Za-z\\|]+', '')
<ipython-input-19-dc66ac357375>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['gun_type'] = df['gun_type'].str.replace('[^A-Za-z\\|]+', '')

In [20]:
df

,incident_id,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,location_description,...,male,female,Adult,Teen,Child,Victim,Suspect,Arrested,Killed,Injured
0,461105,2013-01-01,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,...,3,1,5,0,0,4,1,1,0,4
1,460726,2013-01-01,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,1,0,4,0,0,4,1,0,1,3
2,478855,2013-01-01,Ohio,Lorain,1,3,Unknown||Unknown,Unknown||Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",Cotton Club,...,5,0,5,0,0,3,2,2,1,3
3,478925,2013-01-05,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,...,3,1,4,0,0,3,1,0,4,0
4,478959,2013-01-07,North Carolina,Greensboro,2,2,Unknown||Unknown,Handgun||Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,2,2,3,1,0,3,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,2018-03-31,Louisiana,Rayne,0,0,Unknown,Unknown,Shots Fired - No Injuries,NaN,...,0,1,1,0,0,0,1,1,0,0
239673,1083139,2018-03-31,Louisiana,Natchitoches,1,0,Unknown,Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",Shop Rite,...,2,0,2,0,0,1,1,1,1,0
239674,1083151,2018-03-31,Louisiana,Gretna,0,1,Unknown,Unknown,Shot - Wounded/Injured,NaN,...,1,0,1,0,0,1,0,0,0,1
239675,1082514,2018-03-31,Texas,Houston,1,0,Unknown,Unknown,"Shot - Dead (murder, accidental, suicide)",Vanderbilt Court apartments,...,1,0,1,0,0,1,0,0,1,0
239676,1081940,2018-03-31,Maine,Norridgewock,2,0,Unknown||Unknown,Handgun||Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",NaN,...,1,1,2,0,0,1,1,0,2,0

In [21]:
df['gun_stolen'] = df['gun_stolen'].str.split('\\|\\|')
df['gun_type'] = df['gun_type'].str.split('\\|\\|')
df

,incident_id,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,location_description,...,male,female,Adult,Teen,Child,Victim,Suspect,Arrested,Killed,Injured
0,461105,2013-01-01,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,...,3,1,5,0,0,4,1,1,0,4
1,460726,2013-01-01,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,1,0,4,0,0,4,1,0,1,3
2,478855,2013-01-01,Ohio,Lorain,1,3,"[Unknown, Unknown]","[Unknown, Unknown]","Shot - Wounded/Injured||Shot - Dead (murder, a...",Cotton Club,...,5,0,5,0,0,3,2,2,1,3
3,478925,2013-01-05,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,...,3,1,4,0,0,3,1,0,4,0
4,478959,2013-01-07,North Carolina,Greensboro,2,2,"[Unknown, Unknown]","[Handgun, Handgun]","Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,...,2,2,3,1,0,3,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,2018-03-31,Louisiana,Rayne,0,0,[Unknown],[Unknown],Shots Fired - No Injuries,NaN,...,0,1,1,0,0,0,1,1,0,0
239673,1083139,2018-03-31,Louisiana,Natchitoches,1,0,[Unknown],[Unknown],"Shot - Dead (murder, accidental, suicide)||Ins...",Shop Rite,...,2,0,2,0,0,1,1,1,1,0
239674,1083151,2018-03-31,Louisiana,Gretna,0,1,[Unknown],[Unknown],Shot - Wounded/Injured,NaN,...,1,0,1,0,0,1,0,0,0,1
239675,1082514,2018-03-31,Texas,Houston,1,0,[Unknown],[Unknown],"Shot - Dead (murder, accidental, suicide)",Vanderbilt Court apartments,...,1,0,1,0,0,1,0,0,1,0
239676,1081940,2018-03-31,Maine,Norridgewock,2,0,"[Unknown, Unknown]","[Handgun, Shotgun]","Shot - Dead (murder, accidental, suicide)||Sui...",NaN,...,1,1,2,0,0,1,1,0,2,0

In [22]:
df.shape

(192052, 27)

In [23]:
df.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'n_killed',
       'n_injured', 'gun_stolen', 'gun_type', 'incident_characteristics',
       'location_description', 'n_guns_involved', 'participant_age',
       'participant_relationship', 'gender_list', 'status_list', 'age_list',
       'type_list', 'male', 'female', 'Adult', 'Teen', 'Child', 'Victim',
       'Suspect', 'Arrested', 'Killed', 'Injured'],
      dtype='object')